output-format: pylint
strictness: veryhigh
autodetect: false

ignore-paths:
  - venv
  - __pycache__

pylint:
  enable:
    - useless-suppression
  options:
    max-line-length: 120

pep8:
  options:
    max-line-length: 120